In [ ]:
"""
1)np.random.rand()function

use:
    TO generate random floating point numbers uniformely distributed between 0.0 (inclusive) and 1.0 (exclusive).

syntax:
       import numpy as np
       np.random.rand(d0, d1, d2, ......, dn)

parameter:
           d0, d1, d2, ..., dn:
                                Integers value representing the dimension (shape) of the output array.
                                
            Note:
                 If no arguement is given it returns a single float.
                 
            return value:
                         random number between 0 and 1
                         
"""


In [1]:
# 01Generate_a_singlr_random_number.py
import numpy as np
x=np.random.rand()
print(x)

0.5234147527552707


In [ ]:
# 02generate_a_1-D_array.py
import numpy as np
arr=np.random.rand(5)
print(arr)

[0.98836751 0.95193641 0.1775661  0.62976884 0.08427224]


In [ ]:
# 03Generate 2-D array(matrix).py
import numpy as np
matrix=np.random.rand(3,4)
print(matrix)

[[0.39783386 0.35472517 0.56460392 0.03063354]
 [0.5733139  0.23201046 0.93299627 0.53841465]
 [0.15546551 0.03052984 0.80482762 0.03944521]]


In [ ]:
"""
2)np.random.randint()function

use:
    TO generate random integers within a specified range.

syntax:
       import numpy as np
       np.random.randint(low, high=None, size=None)

Parameters:
           low:
               lowest integer (inclusive)

            hign:
                 highest integer (exclusive)
                 If not given,number are generated from 0 to (low-1)

            size:
                 shape of output (Dimention)

            return values:
                          random number between low (inclusive) and hign (exclusive)
               
"""


4


In [2]:
# 01to Generate single random integer.py
import numpy as np
x=np.random.randint(10)
print(x)

# IT generates a random integer between 0 and 9

6


In [1]:
# 02Generate a random integers between 10 to 20.py
import numpy as np
x=np.random.randint(10,20)
print(x)
# generatres a random integer between 10 and 19

19


In [ ]:
# 03-1D-array_randint().py
import numpy as np
arr=np.random.randint(1,10,size=5)
print(arr)
# generates 5 random integers between 1 and 9

[7 3 2 4 5]


In [20]:
# 04-2D array matrix randint().py
import numpy as np
matrix=np.random.randint(1,100,size=(3,4))
print(matrix)
# generates 3x4 matrix with random integers between 1 and 99

[[37 23 87  8]
 [34 97 43 29]
 [74 24 92 69]]


In [ ]:
"""
3)np.random.randn()function

use:
    To generate numbers from normal distribution with mean=0,sd=1 (SD=Standard Deviation).

syntax:
        import numpy as np
        np.random.randn(d0, d1, ..., dn)

Parameters:
           d0, d1,.....,dn:
                            Dimention (shape) of output Array.

           return value:
                         random floating point numbers from standard normal distribution.



"""

In [3]:
# 01.generate_a_single_random_number.py
import numpy as np
x=np.random.randn()
print(x)

0.6660697560417227


In [21]:
# 02.Generate_a_1_D_array.py
import numpy as np
array=np.random.randn(5)
print(array)

[ 0.30585514 -0.35064702 -1.12495998  1.7442251   0.08647634]


In [6]:
# 03.Generate_a_2D_array (Matrix).py
import numpy as np
matrix=np.random.randn(3,4)
print(matrix)


[[ 0.16609041  0.03792954  0.06883151  1.51491316]
 [-0.11759381  0.36591388 -0.3622587   0.4483195 ]
 [-0.36929917  0.28351417 -1.27299063  2.44756046]]


In [ ]:
"""
4)np.random.normal()function

use:
    To generate random numbers from normal distribution with specified mean and SD

Syntax:
       import numpy as np
       np.random.normal(loc=0.0, scale=1.0, size=None)

Parameters:
           loc:
               Location parameter

           mean:
                 µ of the location , default is 0.0

           scale:
                  SD(σ) of the distribution , default is 1.0

           size:
                 shape(dimention of output)

           return value:
                         random floating point number from normal distribution
"""


In [4]:
# 01_GENERATE_A_SINGLE_RANDOM_NUMBER.PY
import numpy as np
x=np.random.normal()
print(x)

1.9171302368194305


In [2]:
# 02_GENERATE_A_SINGLE_RANDOM_NUMBER_from_N(0,1).PY
import numpy as np
x=np.random.normal(loc=0,scale=1)
print(x)

-0.38109040868938365


In [ ]:
# 03_GENERATE_A_SINGLE RANDOM_NUMBER_FROM_M(50,10).PY
import numpy as np
x=np.random.normal(loc=50,scale=10)
print(x)

60.416927083516015


In [24]:
# 04_GENERATE_1-D_ARRAY.PY
import numpy as np
arr=np.random.normal(loc=50,scale=10,size=5)
print(arr)

[42.14093494 47.33013524 46.34860039 56.9284606  63.12954816]


In [ ]:
# 05_GENERATE_A_2_D_ARRAY.PY
import numpy as np
arr=np.random.normal(loc=50,scale=10,size=(3,4))
print(arr)

[[37.62758422 55.17775635 57.1273077  55.11306898]
 [58.41444378 59.86769173 37.73676397 63.49055345]
 [55.21971309 77.2138394  59.26212069 53.31641283]]


In [ ]:
"""
5)np.random.uniform()function

use:
     to generate random floating point number that are uniformly distributedbetween of specified lower (low) and upper (high) limits

syntax:
        np.random.uniform(low=0.0, high=1.0, size=None)

Parameaters:
             low:
                  lower limit (inclusive) default is 0.0

             hign:
                  upper limit (exclusive) default is 1.0

             size:
                   Dimention (shape) of output

             return value:
                           random floating point number betweeen low (inclusive) and high (exclusive)
                           
    
"""


In [25]:
# 01_GENERATE_A_SINGLE_RANDOM_NUMBER.PY
import numpy as np
x=np.random.uniform()
print(x)


0.5266070309980563


In [ ]:
# 02_GENERATE_A_SINGLE_RANDOM_NUMBER_betwen_00_&_1.0.PY
import numpy as np
x=np.random.uniform(0.0,1.0)
print(x)

0.5627881749035919


In [ ]:
# 03_GENERATE_A_SINGLE_RANDOM_NUMBER_betwen_10_&_20.PY
import numpy as np
x=np.random.uniform(10,20)
print(x)

10.252805349287582


In [ ]:
# 04_GENERATE A 1-D ARRAY
import numpy as np
arr=np.random.uniform(1,5,size=5)
print(arr)

[2.9356398  1.99106291 4.43550977 1.31533525 4.96428652]


In [ ]:
# 05_GENERATE_A_5_RANDOM_FLOATING_POINT_NUMBER_BETWEEN_1_&_5.PY
import numpy as np
arr=np.random.uniform(20,30,size=(3,4))
print(arr)

[[24.90876415 21.79173447 29.76508822 29.76267378]
 [21.99681969 24.28651221 20.02670252 21.03722466]
 [26.31854957 29.79654176 25.69887521 22.5238642 ]]


In [ ]:
# 06_GENERATE_A_2-D_ARRAY(MATRIX).PY
import numpy as np
matrix=np.random.uniform(20,30,size=(3,4))
print(matrix)

[[29.22546958 26.11550188 26.40608962 29.46801285]
 [20.77939793 20.64417871 21.98599221 26.03886556]
 [29.65810516 29.92662567 22.51895233 23.00561859]]


In [ ]:
"""
6)np.arange() function

Use: 
     To create an array of evenly spaced values between specified range

syntax:
        import numpy as np
        np.arange([start],stop,[step],dtype=None)

Parameter:
            Start:
                   starting value (inclusive). default is 0

            Stop:
                  ending value (exclusive) required must

            Step:
                  difference between consecutive values default is 1

            Return Value:
                           numpy array containing evenly spaced value
"""

In [4]:
# 01_create_an_array_from_0_to_9.py
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 02_create_an_array_from_1_to_9.py
import numpy as np
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# 03_create_an_array_with_step.py
import numpy as np
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
# 04_create an_array_with_floating_point_values.py
import numpy as np
arr=np.arange(1.0,5.0,0.5)
print(arr)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
# 05_specify_datatype.py
import numpy as np
arr=np.arange(1,6,dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [8]:
"""
7)np.random.choice()function

Use:
     randomly selects 1 or more elements from a given array or sequence (population) it also selects elements with and without replacement and according to specified probability. 

syntax:
        import numpy as np
        np.random.choise(a,size=None,replace=True,p=None)

Parameters:
            a:
              array like object or an integer
              
              note: 
                    If an integer 'n' is given elements are selected from 0 to (n-1)

            size:
                  number or shape of random sample to generate (optional)

            replace:
                     If True sample is with replacement
                     If false sample is without replacement. Default is True

            P:
               Probability assigned with each element (Optional)

            Return values:
                           Randomlyselectelements or array of randomly selected element
               
                  
"""


In [ ]:
# 01_select_one_random_element.py
import numpy as np
x=np.random.choice([10,20,30,40,50])
print(x)

In [ ]:
# 02_select_5_random_number_from_0_to_9.py
import numpy as np
x=np.random.choice(10,size=5)
print(x)

[2 6 7 2 3]


In [ ]:
# 03.py
import numpy as np
fruits=["apple","orange","banana","mango"]
result=np.random.choice(fruits,size=3)
print(result)

['mango' 'apple' 'orange']


In [ ]:
#04_select_without_replacement
import numpy as np
number=[1,2,3,4,5]
result=np.random.choice(number,size=3,replace=False)
print(result) #here each unit is selected only once

[2 4 1]


In [1]:
#05_select_with_probability
import numpy as np
colors=["red","blue","green",]
result=np.random.choice(colors,size=5)
print(result)

['green' 'blue' 'red' 'green' 'green']


In [10]:
# 8)np.concatenate()function
"""
Use:
     To join two or more array along an existing axis (It Combine multiple arrays into a single array. )

Syntax:
        import numpy as np
        np.concatenate((array1,array2,....),axis=0)

Parameter:
           array1,array2,...:
                              array to be join (combine)

           axis:
                 axis alone which arrays are join. defalut is 0

           Return values:
                          A new numpy array formed by Combining the input arrays.
"""

In [9]:
# 01_concatenate two 1-D array
import numpy as np
a=np.array([1,2,3,])
b=np.array([4,5,6,])
result=np.concatenate((a,b))
print(result)

[1 2 3 4 5 6]


In [4]:
# 02_concatenate_two_2-D_aray.py
import numpy as np
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])
result=np.concatenate((a,b),axis=0)
print(result)
           

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
# 03_concatenate_two_2-D_arrays_column.py
import numpy as np
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])
result=np.concatenate((a,b),axis=1)
print(result)
           

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
"""
9).np.random.shuffle() function

Use:
     To randomly shuffle an element of array it modifies the orignal array unit place.
     It does not create new array.

Syntax:
        import numpy as np
        np.random.shuffle(array)

Parameter:
           array:
                  The numpy array or list whose elements are to be shuffle

           return value:
                         The original array is shuffled directly.
"""


In [13]:
# 01.shuffle_a_1-D_array.py
import numpy as np
array=np.array([1,2,3,4,5])
np.random.shuffle(array)
print(array)

[2 3 5 1 4]


In [2]:
# 02.shuffle_a_list.py
import numpy as np
numbers=[10,20,30,40,50,60]
np.random.shuffle(numbers)
print(numbers)

[40, 30, 20, 10, 60, 50]


In [3]:
# 03.mix_two_array_randomly.py
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.concatenate((a,b))
np.random.shuffle(result)
print(result)

[3 5 1 6 2 4]


In [4]:
# 04.to_draw_srswr.py
#prog-1 to draw srswr
import numpy as np
#define population
p1=np.random.rand(30) #population from u(0,1)
p2=np.random.randint(10,100,size=40) #population of integers
p3=np.random.randn(50) #population from N(0,1)
p4=np.random.normal(50,10,size=60) #population from N(50,100)
p5=np.random.uniform(5,20,size=70) #population from U (5,20)
p6=np.arange(20,40,step=0.5)

#to draw sample

s1=np.random.choice(p1,size=9,replace=True)
s2=np.random.choice(p2,size=12,replace=True)
s3=np.random.choice(p3,size=15,replace=True)
s4=np.random.choice(p4,size=18,replace=True)
s5=np.random.choice(p5,size=21,replace=True)
s6=np.random.choice(p6,size=14,replace=True)

#display result
print("population 1: \n",p1)
print("SRSWR 1: \n",s1)
print("population 1 A.m=",np.mean(p1))
print("sample 1 A.m=",np.mean(s1))

print("population 2: \n",p2)
print("SRSWR 2: \n",s2)
print("population 2 A.m=",np.mean(p2))
print("sample 2 A.m=",np.mean(s2))

print("population 3: \n",p3)
print("SRSWR 3: \n",s3)
print("population 3 A.m=",np.mean(p3))
print("sample 3 A.m=",np.mean(s3))

print("population 4: \n",p4)
print("SRSWR 4: \n",s4)
print("population 4 A.m=",np.mean(p4))
print("sample 4 A.m=",np.mean(s4))

print("population 5: \n",p5)
print("SRSWR 5: \n",s5)
print("population 5 A.m=",np.mean(p5))
print("sample 5 A.m=",np.mean(s5))

print("population 6: \n",p6)
print("SRSWR 6: \n",s6)
print("population 6 A.m=",np.mean(p6))
print("sample 6 A.m=",np.mean(s6))

population 1: 
 [0.56077372 0.25677952 0.40166372 0.85647762 0.71249359 0.13755709
 0.92258951 0.5175416  0.91474501 0.74799503 0.35462838 0.18296401
 0.10782074 0.25876405 0.11727053 0.67183606 0.60745692 0.73906891
 0.25519353 0.35945001 0.36321304 0.02205895 0.27912808 0.45741994
 0.16969604 0.46718754 0.90392398 0.79867894 0.02157136 0.36457884]
SRSWR 1: 
 [0.5175416  0.11727053 0.35945001 0.25677952 0.27912808 0.02157136
 0.67183606 0.13755709 0.5175416 ]
population 1 A.m= 0.4510175422596146
sample 1 A.m= 0.319852873131529
population 2: 
 [58 66 96 94 45 31 48 58 55 18 34 60 63 58 57 87 21 21 70 68 72 90 16 10
 22 29 73 10 27 45 21 31 21 87 84 20 74 15 74 27]
SRSWR 2: 
 [60 74 60 34 21 96 45 74 21 20 31 60]
population 2 A.m= 48.9
sample 2 A.m= 49.666666666666664
population 3: 
 [ 0.08283051  0.61260098  1.42393164 -0.01839869 -0.80738957 -0.17581202
  2.35974068 -1.11167596  0.6156536  -0.99811909 -0.32213621  0.26349411
  1.45280188  0.94455906  0.68881329 -0.01616576  1.12495699

In [5]:
# 05.To_draw_srswor.py
#prog-1 to draw srswr
import numpy as np
#define population
p1=np.random.rand(30) #population from u(0,1)
p2=np.random.randint(10,100,size=40) #population of integers
p3=np.random.randn(50) #population from N(0,1)
p4=np.random.normal(50,10,size=60) #population from N(50,100)
p5=np.random.uniform(5,20,size=70) #population from U (5,20)
p6=np.arange(20,40,step=0.5)

#to draw sample

s1=np.random.choice(p1,size=9,replace=False)
s2=np.random.choice(p2,size=12,replace=False)
s3=np.random.choice(p3,size=15,replace=False)
s4=np.random.choice(p4,size=18,replace=False)
s5=np.random.choice(p5,size=21,replace=False)
s6=np.random.choice(p6,size=14,replace=False)

#display result
print("population 1: \n",p1)
print("SRSWR 1: \n",s1)
print("population 1 A.m=",np.mean(p1))
print("sample A.m=",np.mean(s1))

print("population 2: \n",p2)
print("SRSWR 2: \n",s2)
print("population 2 A.m=",np.mean(p2))
print("sample 2 A.m=",np.mean(s2))

print("population 3: \n",p3)
print("SRSWR 3: \n",s3)
print("population 3 A.m=",np.mean(p3))
print("sample 3 A.m=",np.mean(s3))

print("population 4: \n",p4)
print("SRSWR 4: \n",s4)
print("population 4 A.m=",np.mean(p4))
print("sample 4 A.m=",np.mean(s4))

print("population 5: \n",p5)
print("SRSWR 5: \n",s5)
print("population 5 A.m=",np.mean(p5))
print("sample 5 A.m=",np.mean(s5))

print("population 6: \n",p6)
print("SRSWR 6: \n",s6)
print("population 6 A.m=",np.mean(p6))
print("sample 6 A.m=",np.mean(s6))

population 1: 
 [0.31826125 0.33417397 0.01599535 0.36766203 0.45830481 0.10483432
 0.30566844 0.04674365 0.65548015 0.64082754 0.19547403 0.20307814
 0.4864277  0.11218692 0.57988619 0.90821224 0.44560169 0.17415346
 0.85707069 0.58664295 0.07465156 0.00886793 0.23618603 0.69069858
 0.31535514 0.11623651 0.78670529 0.46891204 0.91490912 0.75745064]
SRSWR 1: 
 [0.31826125 0.17415346 0.4864277  0.75745064 0.20307814 0.85707069
 0.11623651 0.00886793 0.91490912]
population 1 A.m= 0.40555527833368665
sample A.m= 0.42627282521287335
population 2: 
 [81 13 11 32 94 53 65 19 85 37 52 48 83 60 25 61 20 31 84 25 98 15 72 48
 66 88 70 98 98 18 52 50 82 58 87 61 27 20 66 87]
SRSWR 2: 
 [48 27 31 50 87 98 25 88 20 98 61 70]
population 2 A.m= 56.0
sample 2 A.m= 58.583333333333336
population 3: 
 [ 0.56860396  0.49688904  0.26939049 -1.44920519 -0.85417749 -0.95602772
 -0.60386038 -1.39845775  0.2645177  -2.46180894  0.19366114 -0.20465771
  1.48478086 -1.41567632  0.06478555  1.22839052  0.5586824

In [6]:
# 06.prog_3_To_draw_srswr_&_srswor.py
import numpy as np
P = np.random.uniform(5, 45, size=100)
SRSWR = np.random.choice(P, size=15, replace=True)
SRSWOR = np.random.choice(P, size=15, replace=False)
print("Population : \n", P)
print("SRSWR : \n", SRSWR)
print("SRSWOR : \n", SRSWOR)
print("Population A.M = ", np.mean(P))
print("A.M of SRSWR = ", np.mean(SRSWR))
print("A.M of SRSWOR = ", np.mean(SRSWOR)) 

Population : 
 [19.71908988 28.45301039 42.49052717 41.1352343  29.96236439 16.28025431
 19.4034447  41.17568616 42.12377099  9.80956921  9.84368126 34.54087084
 38.02508458 14.24875659 10.45114869 28.52188655 10.86295705 28.19245381
  6.15170483 28.71223977 30.64534208  6.90356662 38.313012   33.82029041
 39.19594604 21.01462626 22.2016597  10.98972607 30.31588272 40.1865689
 28.96270477 24.09091185 13.89500942 19.64320221 30.21244542 10.18366561
 25.8571564  35.04357771 41.12451771 42.43341947 35.12457647 15.88002299
 23.5177281  42.19095861  9.59738823 18.04273183 19.19597892 16.32555781
 20.90226772 11.43235206 11.04844783 13.32931644 44.33875931  6.61254041
  5.67518037  6.71803848 10.96890447 33.31584185 42.67872911 18.35558122
 41.97368353 44.58456864 30.22393793 39.35121357 43.89906506 40.61098457
 40.7955611   6.63135714 26.25204874  7.83882948  6.98858823 11.27456498
 17.43507716 12.62569874 42.77961964 20.66021353 14.15454671 34.34489641
  5.39197631 23.08319737 24.37128291 

In [8]:
# 07.TO_Draw_Stratified_Sample.py
import numpy as np
p1=np.random.rand(30) #stratum 1 from U (0,1)
p2=np.random.rand(40) #stratum 2 from N (0,1)
p3=np.random.uniform(10,20,50) #stratum 3 from U (10,20)
p4=np.arange(50,100,0.5) #stratum 4
hetro=np.concatenate((p1,p2,p3,p4)) # Heterogeneous population
np.random.shuffle(hetro)
print("Hetrogeneous population:\n",hetro)
srswor=np.random.choice(hetro,size=44,replace=False)
print("srswor: \n", srswor)

#To draw sample from each stratum
s1=np.random.choice(p1,size=6,replace=False)
s2=np.random.choice(p2,size=8,replace=False)
s3=np.random.choice(p3,size=10,replace=False)
s4=np.random.choice(p4,size=20,replace=False)

#To form stratified sample
stratified=np.concatenate((s1,s2,s3,s4))
print("stratified sample:\n",stratified)
print("population A.m =",np.mean(hetro))
print("A.m of srswor=",np.mean(srswor))
print("A.m of stratified=",np.mean(stratified))

Hetrogeneous population:
 [1.75937705e+01 6.50000000e+01 9.95000000e+01 6.70000000e+01
 8.50000000e+01 9.45000000e+01 1.69569947e-01 1.40721951e+01
 4.90442484e-02 3.26164177e-01 4.59661931e-01 1.49604458e+01
 9.75000000e+01 1.62379874e+01 1.39565985e+01 2.89347424e-01
 7.99654625e-01 8.15000000e+01 5.00000000e+01 7.60000000e+01
 1.91755951e+01 8.47875843e-01 1.26116695e+01 6.60000000e+01
 1.94511391e+01 1.94683396e+01 5.10000000e+01 8.45000000e+01
 9.25000000e+01 3.76452945e-01 6.90000000e+01 6.54948639e-01
 9.40000000e+01 2.90786364e-01 5.84977956e-01 9.15000000e+01
 1.37929098e+01 9.05000000e+01 7.95000000e+01 2.82508989e-01
 7.85000000e+01 8.65000000e+01 7.70722600e-01 6.30000000e+01
 7.26585747e-01 9.10000000e+01 8.55000000e+01 1.10894643e+01
 1.46665719e+01 8.69022153e-01 9.30000000e+01 8.25000000e+01
 7.15032379e-01 6.82200229e-01 6.10000000e+01 5.51101354e-01
 6.95000000e+01 8.60000000e+01 1.24227314e+01 2.65575298e-01
 6.75000000e+01 6.73863046e-02 1.48881817e-01 5.25000000e+0

In [9]:
# Prog - 5 : To Draw Systematic Sample

import numpy as np
p = np.random.uniform(50, 60, size=150)
print("Population:\n", p)
N = len(p)
print("Population size =", N)
n = int(input("Enter the sample size: "))
K = N // n #No of item in each sequential group 
print("No. of items in each sequential group =", K)
s1 = np.random.randint(0, K) # Selection of first item in first sequential group
systematic = p[s1::K] # slicing
print("Systematic sample:\n", systematic)
print("Population A.M. =", np.mean(p))
print("Systematic Sample A.M. =", np.mean(systematic))

Population:
 [58.0616594  56.64351709 58.54022714 55.74425243 57.63843716 59.20344046
 51.47885211 59.09447944 52.33494374 57.50116138 58.72754085 55.75065268
 54.5675654  56.28219672 50.96996772 50.53845018 59.76010661 52.53007989
 54.06509508 59.71028666 50.42574714 58.42190133 53.96667586 57.27504829
 52.51825791 55.7590434  57.48455594 57.99506392 53.47874569 55.85194267
 53.16715538 55.22743455 51.39250858 58.13647043 54.32560841 53.87852091
 56.77965746 51.72320906 59.08718368 50.70006531 57.12579181 57.94974554
 52.89831308 52.32998051 54.74863779 59.36488646 57.71609336 59.09441581
 54.99691962 53.35885632 55.6685973  52.35990575 52.62985233 55.63603159
 58.63313802 50.8923146  51.93598503 50.40499252 52.07098807 53.45574773
 58.67195354 57.04472535 54.19734943 53.52641069 55.94880687 52.31354239
 55.26296449 57.69635421 59.99875101 50.50735566 53.52957484 51.34645178
 55.21237431 58.49337566 55.53586185 55.86009908 59.55154239 56.99487287
 56.2270791  50.44669357 53.43276509 5

Enter the sample size:  50


No. of items in each sequential group = 3
Systematic sample:
 [56.64351709 57.63843716 59.09447944 58.72754085 56.28219672 59.76010661
 59.71028666 53.96667586 55.7590434  53.47874569 55.22743455 54.32560841
 51.72320906 57.12579181 52.32998051 57.71609336 53.35885632 52.62985233
 50.8923146  52.07098807 57.04472535 55.94880687 57.69635421 53.52957484
 58.49337566 59.55154239 50.44669357 55.18433539 58.43092721 55.83634869
 59.34398789 53.7511172  58.78001268 55.18719224 57.90760414 51.15061855
 55.04502182 57.71541197 50.69689905 55.80293369 56.95513195 51.32355677
 58.54215054 55.63193324 52.7099889  52.9620432  51.93646592 51.75707325
 58.12150036 52.42834008]
Population A.M. = 55.057575930360954
Systematic Sample A.M. = 55.367456522910494
